### ISSUE TITLE
Screenshot missing

### ISSUE THREAD

**Issue by damithc** [kerwin97/duke#9]
@kerwin97 your iP screenshot missing from https://nus-cs2103-ay1920s1.github.io/website/admin/ip-showcase.html#lim-s-erwin-kerwin97

Can fix?

**Comment by kerwin97** [comment]
Dear Prof,

Sure thing! So sorry!!! I was sure I uploaded already

Best Regards,
Kerwin Lim

On 7 Oct 2019, at 4:17 PM, Damith C. Rajapakse <notifications@github.com<mailto:notifications@github.com>> wrote:


@kerwin97<https://github.com/kerwin97> your iP screenshot missing from https://nus-cs2103-ay1920s1.github.io/website/admin/ip-showcase.html#lim-s-erwin-kerwin97

Can fix?

**Comment by kerwin97** [comment]
Found the error, I named it UI.png instead of Ui.png. Have reuploaded it so sorry!

**Comment by damithc** [comment]
> Found the error, I named it UI.png instead of Ui.png. Have reuploaded it so sorry!

👍
